spring.application.name=gestor-investimento

spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${DB_NAME:gestor_investimento}
spring.datasource.username=${DB_USERNAME:gestor_investimento}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.flyway.enabled=true
spring.flyway.default-schema=public
spring.flyway.schemas=public

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.default_schema=public

spring.jackson.deserialization.fail-on-unknown-properties=true

integration.cnpj.brasil-api.base-url=${BRASIL_API_BASE_URL:https://brasilapi.com.br}
integration.cnpj.brasil-api.connect-timeout=${BRASIL_API_CONNECT_TIMEOUT:2s}
integration.cnpj.brasil-api.read-timeout=${BRASIL_API_READ_TIMEOUT:5s}
