CREATE TABLE corretoras (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cnpj VARCHAR(14) NOT NULL,
    razao_social VARCHAR(150) NOT NULL,
    nome_fantasia VARCHAR(150),
    email VARCHAR(254),
    telefone VARCHAR(20),
    cep VARCHAR(8) NOT NULL,
    logradouro VARCHAR(150) NOT NULL,
    numero VARCHAR(20) NOT NULL,
    complemento VARCHAR(100),
    bairro VARCHAR(100) NOT NULL,
    cidade VARCHAR(100) NOT NULL,
    uf VARCHAR(2) NOT NULL,
    situacao_cadastral VARCHAR(30) NOT NULL,
    validada_na_cvm BOOLEAN NOT NULL,
    data_cadastro TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_corretoras_cnpj UNIQUE (cnpj)
);
