CREATE TABLE acoes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticker VARCHAR(20) NOT NULL,
    nome_empresa VARCHAR(150) NOT NULL,
    mercado VARCHAR(20) NOT NULL,
    moeda VARCHAR(3) NOT NULL,
    cotacao_atual NUMERIC(19,4) NOT NULL,
    data_hora_cotacao TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT ck_acoes_mercado CHECK (mercado IN ('BRASIL', 'ESTADOS_UNIDOS')),
    CONSTRAINT ck_acoes_moeda CHECK (moeda IN ('BRL', 'USD')),
    CONSTRAINT uk_acoes_ticker_mercado UNIQUE (ticker, mercado)
);
