CREATE TABLE carteiras (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    nome_normalizado VARCHAR(100) NOT NULL,
    descricao VARCHAR(500),
    data_cadastro TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_carteiras_nome_normalizado UNIQUE (nome_normalizado)
);
