CREATE TABLE operacoes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    carteira_id BIGINT NOT NULL,
    acao_id BIGINT NOT NULL,
    tipo VARCHAR(10) NOT NULL,
    quantidade DECIMAL(19,8) NOT NULL,
    preco_unitario DECIMAL(19,8) NOT NULL,
    data_operacao TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_operacoes_carteira FOREIGN KEY (carteira_id) REFERENCES carteiras(id),
    CONSTRAINT fk_operacoes_acao FOREIGN KEY (acao_id) REFERENCES acoes(id),
    CONSTRAINT ck_operacoes_tipo CHECK (tipo IN ('COMPRA','VENDA')),
    CONSTRAINT ck_operacoes_quantidade CHECK (quantidade > 0),
    CONSTRAINT ck_operacoes_preco CHECK (preco_unitario > 0)
);
CREATE INDEX idx_operacoes_carteira_data ON operacoes(carteira_id, data_operacao, id);
