CREATE TABLE cotacoes_historicas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    acao_id BIGINT NOT NULL,
    cotacao NUMERIC(19,8) NOT NULL,
    data_hora_cotacao TIMESTAMP WITH TIME ZONE NOT NULL,
    data_registro TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_cotacoes_historicas_acao FOREIGN KEY (acao_id) REFERENCES acoes(id),
    CONSTRAINT ck_cotacoes_historicas_cotacao_positiva CHECK (cotacao > 0)
);

CREATE INDEX ix_cotacoes_historicas_acao_data
    ON cotacoes_historicas (acao_id, data_hora_cotacao, id);
